---
- name: Installing MongoDB
  hosts: all
  tasks:
    - name: updating cache
      apt:
        update_cache: yes
      become: yes
    - name: installing utlis
      apt:
        name: "{{ item }}"
        state: present
      become: yes
      loop:
        - wget
        - curl
        - gnupg2
        - software-properties-common
        - apt-transport-https
        - ca-certificates
        - lsb-release
    - name: Import the MongoDB public GPG Key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-6.0.asc
        keyring: /etc/apt/trusted.gpg.d/mongodb-6.gpg
        state: present
      become: yes
    - name: Configure MongoDB Repo
      shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
      become: yes
    - name: Install libssl
      apt:
        deb: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
      become: yes
    - name: updating cache
      apt:
        update_cache: yes
      become: yes
    - name: Install mongodb-org
      apt:
        name: mongodb-org
        state: present
      become: yes
    - name: Enabling mongodb
      systemd:
        name: mongod
        enabled: yes
      become: yes
    - name: Edit configuration file
      copy:
        src: mongod.conf.j2
        dest: /etc/mongod.conf
        remote_src: false
      become: yes
    - name: Restart mongodb
      systemd:
        name: mongod
        state: restarted
      become: yes
    - name: Allow all access to port 27017
      ufw:
        rule: allow
        port: '27017'
    - name: Stopping mongodb
      systemd:
        state: stopped
      become: yes
    - name: creating directory
      file:
        path: /newdata/mongo
        group: mongodb
        owner: mongodb
        state: directory
        mode: 0777
      become: yes
    - name: Copying content from former path to the new directory
      ansible.posix.synchronize:
        src: /var/lib/mongodb
        dest: /newdata/mongo
      become: yes
    - name: Rename the old directory to a backup file
      copy:
        src: /var/lib/mongodb
        dest: /var/lib/mongodb.bak
        remote_src: yes
      become: yes
    - name: Removing old file
      file:
        path: /var/lib/mongodb
        state: absent
      become: yes
    - name: Create a symbolic link to the new directory
      file:
        src: /newdata/mongo
        path: /var/lib/mongodb
        state: link
      become: yes
    - name: Restart MongoDB Service
      systemd:
        name: mongod
        daemon_reload: yes
        state: started
      become: yes
